// pipeline/masechtotDapim.js
//
// טווח דפים לכל מסכת - {start, end} (תמיד מתחילה מכ"ה, לא ב' כמו כולן).
// חולץ ישירות מהקובץ שסיפק המשתמש ("נתיבים שתחת תלמוד בבלי.txt").

module.exports = {
  'ברכות': { start: 2, end: 64 },
  'שבת': { start: 2, end: 157 },
  'עירובין': { start: 2, end: 105 },
  'פסחים': { start: 2, end: 121 },
  'שקלים (ירושלמי)': { start: 2, end: 22 },
  'ראש השנה': { start: 2, end: 35 },
  'יומא': { start: 2, end: 88 },
  'סוכה': { start: 2, end: 56 },
  'ביצה': { start: 2, end: 40 },
  'תענית': { start: 2, end: 31 },
  'מגילה': { start: 2, end: 32 },
  'מועד קטן': { start: 2, end: 29 },
  'חגיגה': { start: 2, end: 27 },
  'יבמות': { start: 2, end: 122 },
  'כתובות': { start: 2, end: 112 },
  'גיטין': { start: 2, end: 90 },
  'קידושין': { start: 2, end: 82 },
  'נדרים': { start: 2, end: 91 },
  'נזיר': { start: 2, end: 66 },
  'סוטה': { start: 2, end: 49 },
  'בבא קמא': { start: 2, end: 119 },
  'בבא מציעא': { start: 2, end: 119 },
  'בבא בתרא': { start: 2, end: 176 },
  'סנהדרין': { start: 2, end: 113 },
  'מכות': { start: 2, end: 24 },
  'שבועות': { start: 2, end: 49 },
  'עבודה זרה': { start: 2, end: 76 },
  'הוריות': { start: 2, end: 14 },
  'זבחים': { start: 2, end: 120 },
  'מנחות': { start: 2, end: 110 },
  'חולין': { start: 2, end: 142 },
  'בכורות': { start: 2, end: 61 },
  'ערכין': { start: 2, end: 34 },
  'תמורה': { start: 2, end: 34 },
  'כריתות': { start: 2, end: 28 },
  'מעילה': { start: 2, end: 22 },
  'תמיד': { start: 25, end: 33 },
  'נדה': { start: 2, end: 73 },
};
